source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'CobraAppTest' do
  pod 'Cobra-iOS', '~> 2.0.1'
end

target 'CobraAppTestUITests' do
  pod 'Cobra-iOS', '~> 2.0.1'
end

target 'PerformanceTest' do
  pod 'Cobra-iOS', '~> 2.0.1'
end
