source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'CobraAppTest' do
  pod 'Cobra-iOS', '~> 1.2.0'
end

target 'CobraAppTestUITests' do
  pod 'Cobra-iOS', '~> 1.2.0'
end

target 'PerformanceTest' do
  pod 'Cobra-iOS', '~> 1.2.0'
end
