name: Run filedemo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  audio_path:
    required: true

runs:
  using: "composite"
  steps:
  - name: demo
    run: >
      ./build/cobra_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -w ${{ inputs.audio_path }}
    working-directory: demo/c
    shell: bash
