name: iOS BrowserStack Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ios-browserstack.yml'
      - 'binding/ios/CobraAppTest/**'

  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - '.github/workflows/ios-browserstack.yml'
      - 'binding/ios/CobraAppTest/**'


defaults:
  run:
    working-directory: binding/ios/CobraAppTest

jobs:
  build:
    name: Run iOS Tests on BrowserStack
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run:
          pip3 install requests

      - name: Make build dir
        run: mkdir ddp

      - name: Inject AccessKey
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          CobraAppTestUITests/CobraAppTestUITests.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing
          -configuration Debug
          -project CobraAppTest.xcodeproj
          -sdk iphoneos
          -scheme CobraAppTest
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Generating ipa
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          mkdir Payload &&
          cp -r CobraAppTest.app Payload &&
          zip --symlinks -r CobraAppTest.ipa Payload &&
          rm -r Payload

      - name: Zipping Tests
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          zip --symlinks -r CobraAppTestUITests.zip CobraAppTestUITests-Runner.app

      - name: Run tests on BrowserStack
        run: python3 ../../../script/automation/browserstack.py
          --type xcuitest
          --username "${{secrets.BROWSERSTACK_USERNAME}}"
          --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
          --project_name "Cobra-iOS"
          --devices "ios-min-max"
          --app_path "ddp/Build/Products/Debug-iphoneos/CobraAppTest.ipa"
          --test_path "ddp/Build/Products/Debug-iphoneos/CobraAppTestUITests.zip"