name: Node.js Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'binding/nodejs/perf.test.js'
      - 'lib/common/**'
      - 'lib/node/**'
      - '.github/workflows/nodejs-perf.yml'

  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/nodejs/perf.test.js'
      - 'lib/common/**'
      - 'lib/node/**'
      - '.github/workflows/nodejs-perf.yml'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  perf-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0
          - os: windows-latest
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0
          - os: macos-latest
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=50 --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}

  perf-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      fail-fast: false
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]
        include:
          - machine: rpi3-32
            num_test_iterations: 50
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0
          - machine: rpi3-64
            num_test_iterations: 50
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0
          - machine: rpi4-32
            num_test_iterations: 50
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0
          - machine: rpi4-64
            num_test_iterations: 50
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0
          - machine: jetson
            num_test_iterations: 50
            init_performance_threshold_sec: 1.0
            proc_performance_threshold_sec: 1.0

    steps:
      - uses: actions/checkout@v3

      - name: Pre-build dependencies
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Machine state before
        working-directory: res/scripts
        run: bash machine-state.sh

      - name: Test
        run: yarn test perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=20 --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}

      - name: Machine state after
        working-directory: res/scripts
        run: bash machine-state.sh
