name: Rust Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'binding/rust/**/*.rs'
      - 'demo/rust/**/*.rs'
      - '.github/workflows/rust-codestyle.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/rust/**/*.rs'
      - 'demo/rust/**/*.rs'
      - '.github/workflows/rust-codestyle.yml'

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash

jobs:
  check-rust-binding-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust pre-build
      run: bash copy.sh
      working-directory: binding/rust

    - name: Rust dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libasound2-dev -y

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run clippy
      run: cargo clippy -- -D warnings
      working-directory: binding/rust

  check-rust-filedemo-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libasound2-dev -y

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run clippy
      run: cargo clippy -- -D warnings
      working-directory: demo/rust/filedemo

  check-rust-micdemo-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Rust dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt install libasound2-dev -y

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run clippy
      run: cargo clippy -- -D warnings
      working-directory: demo/rust/micdemo